### ISSUE TITLE
Boost and other important libs

### ISSUE THREAD

**Issue by Spidy104** [brechtsanders/winlibs_recipes#1]
Hey, Brecht, awesome work btw, is it possible to incorporate some awesome libs like, boost or abseil or fmt, in the installation, it would be really helpful.

**Comment by brechtsanders** [comment]
I'm already on it, but this will be separate from the build tools.

I'm writing a package manager here: https://github.com/brechtsanders/winlibs_tools/

The build recipes (which are to be used under MSYS2 shell) are already published here: https://github.com/brechtsanders/winlibs_tools/

Currently I have over 2400 working recipes!

To make this usable the tools still need some work to get the recipes via Internet and I need to figure out if it's actually okay to publish binary packages for all these libraries and applications.

**Comment by Spidy104** [comment]
So do we use it(like install packages...)

**Comment by brechtsanders** [comment]
Writing a manual is also on the to do list...
