### ISSUE TITLE
Could you add juCi++?

### ISSUE THREAD

**Issue by 3oheicrw** [brechtsanders/winlibs_recipes#15]
This is juCi++: https://gitlab.com/cppit/jucipp

It supports MSYS2 but I don't know why MSYS2 doesn't already have a package for it:

https://gitlab.com/cppit/jucipp/-/blob/master/docs/install.md#windows-with-msys2-httpsmsys2githubio

**Comment by brechtsanders** [comment]
An attempt was already started, but no success yet.
See: https://github.com/brechtsanders/winlibs_recipes/blob/main/recipes_work_in_progress/jucipp.winlib
