### ISSUE TITLE
Recipe wsaerror no longer builds. Source code no longer available.

### ISSUE THREAD

**Issue by Frank-Wong-CN** [brechtsanders/winlibs_recipes#16]
Hi!

I've been trying to build things from your recipes. One of the recipe `wsaerror.winlib`, which is depended by `wxWidgets.winlib`, no longer compiles because the website no longer hosts the source code. I have looked everywhere from Google to Wayback Machine but to no avail. Another recipe `winerr.winlib` by the same author may be unavailable as well.

There is another problem. If `$TARBALLDIR` starts with `/c/`, `tar`, for some reason I don't know yet, will interpret this as `C:\`, which will result in a error: `tar: Cannot connect to C: resolve failed`. I solved this by adding `--force-local` to every `tar` command.

**Comment by brechtsanders** [comment]
I'm not sure that wsaerror is needed for wxWidgets anymore, have you tried building without it?

But you're right, wsaerror en winerror source tarballs seem to have disappeared from Internet.

About your `tar` issue. Are you using the one from MSYS2 shell? I do and have seen no such errors so far.

**Comment by Frank-Wong-CN** [comment]
I'm still facing some obstacles on building `wxWidgets`, but building `unbound` without `wsaerror` is a success, which is the only package that depends on `wsaerror` deep in the dependency tree :)

`winerr`, on the other hand, does not seem to be depended by anything.

On the `tar` issue, yes, I am using `tar` shipped with MSYS2. (I checked this by `which tar` and it gives me `/usr/bin/tar`)

I tested this again with `cppunit.winlib`. I added an `echo` just before `tar` and it gives me this:

```
$ wl-download -v -d $TARBALLDIR/$BASENAME $DOWNLOADSOURCEURL
http://downloads.sourceforge.net/cppunit/cppunit-1.12.1.tar.gz
File already exists: C:/Users/Frank/Documents/Codes/Support/wpm/cache/cppunit\cppunit-1.12.1.tar.gz
$ wl-wait4deps
Checking dependencies for cppunit
$ echo $TARBALLDIR/$BASENAME/$BASENAME-$VERSION.tar.gz
C:/Users/Frank/Documents/Codes/Support/wpm/cache/cppunit/cppunit-1.12.1.tar.gz
$ tar xfz $TARBALLDIR/$BASENAME/$BASENAME-$VERSION.tar.gz
tar (child): Cannot connect to C: resolve failed
```

You can see `TARBALLDIR` is giving "C:\" on both `wl-download` and `tar`. However, when I type `echo $TARBALLDIR`, it gives me `/c/Users/Frank/Documents/Codes/Support/wpm/cache`. It is fixed by appending `--force-local` at the end of the `tar` command.

**Comment by brechtsanders** [comment]
I never came across your issue, and I have been using different MSYS2 versions over time.
However more people had your issue it seems:
- https://github.com/openvenues/libpostal/issues/501
- https://github.com/commercialhaskell/pantry/issues/23
- https://stackoverflow.com/questions/12823499/windows-command-line-tar-cannot-connect-to-d-resolve-failed-with-chef-knife

The last link refers to a solution described [here](https://unix.stackexchange.com/questions/13377/tar-extraction-depends-on-filename/13381#13381).

I have no idea why you have this issue and I don't on any of my systems or any of the MSYS2 versions.

Is your MSYS2 install recent?

**Comment by Frank-Wong-CN** [comment]
Yes. This MSYS2 installation was made in Jun 2022. The version of `tar` is 1.34. Back to that `cppunit` recipe test. I extracted the same package with the same `$TARBALLDIR` variable on MSYS2 terminal manually, and it worked even without `--force-local`.

I have looked into your `wl-build` source code, and I found a place that calls `GetEnvironmentStringsA`. I extracted that part of the code and wrote a test program which prints all environment variables. Compiled with your Windows native MinGW/GCC and MSYS2 MinGW/GCC. Here is what I got:

I set a variable called `PATHTEST2 = /c/Users/Frank/Documents` on both Windows environment and MSYS environment.

Both compiled executables running natively on Windows machine, I got: `PATHTEST2 = /c/Users/Frank/Documents`
Both compiled executables running in MSYS2, I got: `PATHTEST2 = C:/Users/Frank/Documents`

So this problem might involves how my installaion of MSYS2 treats `GetEnvironmentStringsA`? Transforming `/c/` into `C:\` in MSYS environment is indeed more user-friendly, but in this case it is quite unexpected :)

**Comment by brechtsanders** [comment]
That kind of transformation is usually done by the Cygwin/MSYS POSIX-layer.

Is it possible you're compiling for MSYS2 (i.e. with the Cygwin-like POSIX layer)?

The winlibs tools are intended to be built for native Windows / MinGW-w64.

**Comment by Frank-Wong-CN** [comment]
Oh, I see... Yes. The winlibs tools and recipes are executed in MSYS2. I thought the shell commands are intended to be executed in MSYS2 environment with Cygwin/MSYS POSIX-layer.

I didn't build winlibs tools myself. The winlibs tools I'm using are downloaded from the release page.

The test program I mentioned is built both natively in Windows and in MSYS2 with POSIX-layer, the produced results are identical, i.e. when running in MSYS2 with POSIX-layer, `/c/` is transformed to `C:\`, regardless of where the program is being built.

I see where my problem is. The winlibs tools are intended to run under native Windows with MinGW-w64 runtime and a working MSYS2 shell, not in MSYS2 environment with Cygwin/MSYS POSIX-layer.

**Comment by brechtsanders** [comment]
About the `tar: Cannot connect to C: resolve failed` issue:. I have added `--force-local` to all my recipes.
