### ISSUE TITLE
OT: suggestion: can you add libquickmail here in github?

### ISSUE THREAD

**Issue by asmwarrior** [brechtsanders/winlibs_recipes#17]
[libquickmail download | SourceForge.net](https://sourceforge.net/projects/libquickmail/)

I see this is a nice tool, but I don't see there are some discussion or forum for this tool.

I suggest you can add(move) one code repo to github here, thanks!

**Comment by brechtsanders** [comment]
Done

https://github.com/brechtsanders/libquickmail
