### ISSUE TITLE
FR: add lite-xl-plugins

### ISSUE THREAD

**Issue by iahung2** [brechtsanders/winlibs_recipes#19]
https://github.com/lite-xl/lite-xl-plugins

**Comment by brechtsanders** [comment]
Recipe created here: https://github.com/brechtsanders/winlibs_recipes/blob/main/recipes/lite-xl-plugins.winlib

As this would not be part of the actual build tools it will not be included in the build tools.

In the future, please post any package build request here: https://github.com/brechtsanders/winlibs_recipes/issues
