### ISSUE TITLE
Should it work with the Cygwin shell?

### ISSUE THREAD

**Issue by 3oheicrw** [brechtsanders/winlibs_recipes#2]
Why a MSYS2 shell is required? After all if it's just a POSIX shell needed, Cygwin shell served that well. You will use your MinGW distribution to build the recipes anyway so the Cygwin GCC is not involved. If it's needed a base Cygwin shell without Cygwin GCC could be used too. Please consider.

**Comment by 3oheicrw** [comment]
@brechtsanders What do you think about it?

**Comment by 3oheicrw** [comment]
I tried to build the FOX toolkit on Cygwin but with the winlibs.com's GCC. The compilation is fine but it failed at linking. It seems winlibs.com's GCC is a native Win32 program so it doesn't understand Cygwin paths isn't it? What I mean is path like this: /usr/lib /usr/local/lib. But it's strange as it's the same kind of path being used on MSYS2. What did I missed?

BTW, the Cygwin's version of MINGW (not Cygwin GCC) did work. It's not exactly like normal MINGW, it's a cross compiler that cross compile from Cygwin to Win32.

**Comment by 3oheicrw** [comment]
Could cygpath be used to workaround this?

https://cygwin.com/cygwin-ug-net/cygpath.html

**Comment by brechtsanders** [comment]
- Cygwin provides a POSIX compatibility layer, which is linked into your applications/libraries.
- MinGW/MinGW-w64 on the other hand results in native Windows applications/libraries.
- MSYS/MSYS2 itself is a shell providing *nix/POSIX functionality (and was itself written with Cygwin).

So in MSYS2 shell you can use *nix style paths, which it will convert to Windows paths before passing them to your applications.
Cygwin aplications however come with a whole layer that support this paths.
MinGW/MinGW-w64 is pure Windows, so you should forget about *nix style paths. But I see this as a positive thing: no compatibility layer is dragged into your applications/libraries, and they work as any other Windows applications (which is less confusing for the end-user) at native Windows speed. So MinGW/MinGW-w64 can be used on Windows without cross-compiling (which is the goal of https://winlibs.com/).
