### ISSUE TITLE
It should work with the Mozilla Build shell isn't it?

### ISSUE THREAD

**Issue by 3oheicrw** [brechtsanders/winlibs_recipes#3]
The Mozilla Build shell is just a normal MSYS2 shell without the burden of rolling release like MSYS2 since it's fixed release:

https://wiki.mozilla.org/MozillaBuild

I got sick of pacman -Syu and there are hundreds of packages needed to upgrade everytime.

**Comment by brechtsanders** [comment]
The winlibs build environment only needs MSYS2 set up once only for shell purposes. It will have its own package manager (part of https://github.com/brechtsanders/winlibs_tools).
