### ISSUE TITLE
FR: add ecode

### ISSUE THREAD

**Issue by iahung2** [brechtsanders/winlibs_recipes#41]
https://github.com/SpartanJ/eepp/

This is the command I used:

```
premake5 gmake2
make config=release_x86_64 -C make/windows ecode
```

If not specify `ecode`, it will build everything, including demos.

**Comment by brechtsanders** [comment]
Recipe created, but build fails with:
```
Error: invalid value 'ARM64' for architecture
```

**Comment by iahung2** [comment]
> Recipe created, but build fails with:
> 
> ```
> Error: invalid value 'ARM64' for architecture
> ```

The command I posted is for building for `x86_64`.

**Comment by iahung2** [comment]
@brechtsanders Use this command for ARM64:

```
make config=release_arm64 -C make/windows ecode
```

**Comment by brechtsanders** [comment]
But I wasn't on ARM64, I was on x86_64, so the detection was wrong somehow
