### ISSUE TITLE
Can I request a new recipes?

### ISSUE THREAD

**Issue by ghost** [brechtsanders/winlibs_recipes#6]
Like the title.

**Comment by buguorenjian** [comment]
I will try requesting new recipes anyway. If you don't want it then just close it.

**Comment by brechtsanders** [comment]
I looked at your requests (#7 #8 #9 #10 #11 #12 #13 #14).
- FOX Toolkit (#7) already had a working recipe.
- TEA Text Editor (#8) built right out of the box.
- The others didn't build out of the box.

Those that don't build (yet) I added to my [work in progress](https://github.com/brechtsanders/winlibs_recipes/tree/main/recipes_work_in_progress) folder so I get notified if there are any new versions, so I can try again in the future.
