### ISSUE TITLE
Why don't you reuse existing frameworks?

### ISSUE THREAD

**Issue by vmz9poa5** [brechtsanders/winlibs_recipes#81]
e.g: pkgsrc, ravenports,... They are for Unix but can be adapted for Windows. Your recipes are just a bunch of unorganized shell scripts.

**Comment by brechtsanders** [comment]
See also #80 

I have created build and packaging tools. The recipes are indeed shell scripts, but they are used by the build scripts.
This has the advantage the build scripts can be created and tweaked manually outside of the build system too.

I still need to create proper instructions on how to set up such build environment (which involves setting up MSYS2 shell).
