### ISSUE TITLE
Build from source mode like FreeBSD's ports

### ISSUE THREAD

**Issue by vmz9poa5** [brechtsanders/winlibs_recipes#82]
Since there are no binary packages, I have to resort to building from source. But I need to know how to do it.

I currently have MSYS2 installed. Only the core MSYS. I have disabled the MinGW-w64 related repositories in pacman.

**Comment by vmz9poa5** [comment]
Your effort is a big waste of time and will lead to nowhere. But it's your time, you can spend it on whatever you want.

**Comment by brechtsanders** [comment]
> Your effort is a big waste of time and will lead to nowhere.

I would love to learn from your opinion. Why exactly do you think this?

Building packages from source has lead me to build the winlibs compiler tools builds, and they seem to be quite successful.

I currently see 2 main groups of users:
- people who don't wan't to use Unix-like shell (like MSYS) (beginners, IDE users)
- CI build environments who require fast and easy setup and cleanup
